### ISSUE TITLE
Is littler compatible with argparser?

### ISSUE THREAD

**Issue by speechchemistry** [eddelbuettel/littler#107]
Thanks for this great tool. It might be something I'm doing wrong but I can't seem to get littler working with argparser. Are they compatible? Using the example R script "round.R" at https://cran.r-project.org/web/packages/argparser/readme/README.html , I can run it with Rscript:

```
$ Rscript round.R 5.6
6
````
but not littler
```
$ r round.R 5.6
...
Error in parse_args(p) :
  Missing required arguments: expecting 1 values but got 0 values: ().
```

**Comment by eddelbuettel** [comment]
That may have to do with littler using a vector `argv[]` (just like C programs) where as R and Rscript insist on the less useful `commandArgs()` which is not only a) different from standard (C) programming practice, b) longer and c) _requires_ you to call with `commandArgs(trailingOnly = FALSE)`.

Because of these third point, it it hard to do something plugin-compatiable, though the [docopt](https://cran.r-project.org/web/packages/docopt/) author did.  We have dozens of examples in the included [examples/](https://github.com/eddelbuettel/littler/tree/master/inst/examples) directory.

Because the `littler` package can only use what a command-line parser offers, I think you have to talk to its author to see if he wanted to make his package compatiable. I can help, if needed, but should not have to.

**Comment by speechchemistry** [comment]
Thank you for the helpful explanation. I have also [raised an issue with argparser](https://bitbucket.org/djhshih/argparser/issues/33/make-compatible-with-littler).
