### ISSUE TITLE
What is this about?

### ISSUE THREAD

**Issue by raffaem** [eddelbuettel/littler#120]
I don't understand what this package is about.

I can reproduce all the examples with base R.

Can you clarify?

```
➜  cat test.R
#!/usr/bin/env Rscript
print("ciao")

➜  pacman -Qo Rscript
/usr/bin/Rscript is owned by r 4.4.1-1

➜  ./test.R
[1] "ciao"
```

```
➜  Rscript test.R 
[1] "ciao"
```

```
➜  R -e "print('ciao')"
> print('ciao')
[1] "ciao"
```
```
❯ echo "print('ciao')" | R
> print('ciao')
[1] "ciao"
```

**Comment by eddelbuettel** [comment]
You tell me.  What purpose does this issue ticket serve?

**Comment by raffaem** [comment]
> You tell me. What purpose does this issue ticket serve?

I accidentally pressed the Send button before writing the message. I have now edited it.

**Comment by eddelbuettel** [comment]
The difference can be seen on an installed (Unix) system (macOS has issues due to lower-case/upper-case):

```
edd@rob:~$ ls -l /usr/bin/r /usr/bin/R
-rwxr-xr-x 1 root root 118608 Dec 23  2023 /usr/bin/r
-rwxr-xr-x 1 root root   9061 Jun 16 20:08 /usr/bin/R
edd@rob:~$ 
```

and then e.g. doing `ldd` or `file` on it.  _When `littler` was first written_ the entry point `R` was a shell script that started slower.  `Rscript` did not yet exist.

So `r` offers different ways to interact with R (the language and interpreter) which it embeds.  The very first paragraph in the README.md details the four different ways to launch:

```sh
#!/usr/bin/env r              ## can build easy 'shell scripts'

other input | r               ## for use in pipes, using stdin is much harder with R

r somefile.R                  ## for running files, which is something R did not do at the time requiring R CMD BATCH

r -e 'expr'                   ## for evaluating expressions

r --help                      ## to show a quick synopsis
```

and because `r` does fewer things than `R` at startup, it [starts faster](https://dirk.eddelbuettel.com/blog/2014/09/02/).

I personally use it multiple times each day via helper scripts (see [inst/examples](https://github.com/eddelbuettel/littler/tree/master/inst/examples) here).  "Works for me."

**Comment by raffaem** [comment]
> The very first paragraph in the README.md details the four different ways to launch:

These are the exact ways I reproduced in my first post in the exact same order (shell script, cli pipe, run file, run expression), with base R.

So nowadays the only advantage of using `r` over `R` is speed?
Or there are no advantages?

**Comment by eddelbuettel** [comment]
Dear @raffaem -- this is a 20 year old and _widely used project_ for which we have _documentation you could read_.  You just asked me to explain it to you, which I did.

Why are asking the same question?   It is one open source repo.  If *you* don't like it or don't want to use it, fine.  Just move on to another.
